# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        logo:
            quality: 100
            filters:
                scale:
                    dim: [350, 150]

        logo2:
            quality: 100
            filters:
                scale:
                    dim: [400, 150]

        logo3:
            quality: 100
            filters:
                scale:
                    dim: [400, 400]

        pdf:
            quality: 90
            filters:
                scale:
                    dim: [100, 250]
